/**
 * ⚠️  DEMO DATA — SYNTHETIC, NOT REAL BUSINESS INVENTORY  ⚠️
 *
 * Everything this script inserts is fabricated for development and testing:
 * product titles, part numbers, prices, stock levels and the demo accounts.
 * None of it describes real stock, real pricing, or a real business. Product
 * images are schematic SVG drawings generated by scripts/generate-images.mjs,
 * not photographs of actual parts.
 *
 * Run: npm run db:seed        (idempotent — safe to re-run)
 */
import './env';
import { sql } from 'drizzle-orm';
import { getDb, closePool, withTransaction } from '../src/infrastructure/db/client';
import {
  brands, categories, inventory, inventoryEvents, productFitments, productImages,
  productReferences, productSpecs, products, shippingMethods, shippingRates,
  storeSettings, users, vehicleBrands, vehicleEngines, vehicleGenerations,
  vehicleModels, vehicleTrims,
} from '../src/infrastructure/db/schema';
import { getOrCreateConfiguration } from '../src/application/fitment-service';
import { hashPassword } from '../src/lib/crypto';

const DEMO_BANNER = 'داده نمایشی — این محصول صرفاً برای نمایش و آزمایش سامانه ثبت شده است.';

/* ── categories ─────────────────────────────────────────────────────── */

const CATEGORIES: {
  slug: string; nameFa: string; nameEn: string; icon: string; image: string;
  description: string; children?: { slug: string; nameFa: string; nameEn: string }[];
}[] = [
  {
    slug: 'filters', nameFa: 'فیلترها', nameEn: 'Filters', icon: 'filter', image: '/demo/cat-filters.svg',
    description: 'فیلتر روغن، هوا، سوخت و کابین برای خودروهای سواری داخلی و وارداتی.',
    children: [
      { slug: 'oil-filters', nameFa: 'فیلتر روغن', nameEn: 'Oil Filters' },
      { slug: 'air-filters', nameFa: 'فیلتر هوا', nameEn: 'Air Filters' },
      { slug: 'cabin-filters', nameFa: 'فیلتر کابین', nameEn: 'Cabin Filters' },
      { slug: 'fuel-filters', nameFa: 'فیلتر سوخت', nameEn: 'Fuel Filters' },
    ],
  },
  {
    slug: 'brakes', nameFa: 'لنت و سیستم ترمز', nameEn: 'Brakes', icon: 'brake', image: '/demo/cat-brakes.svg',
    description: 'لنت جلو و عقب، دیسک ترمز و لوازم جانبی سیستم ترمز.',
    children: [
      { slug: 'brake-pads', nameFa: 'لنت ترمز', nameEn: 'Brake Pads' },
      { slug: 'brake-discs', nameFa: 'دیسک ترمز', nameEn: 'Brake Discs' },
    ],
  },
  {
    slug: 'engine', nameFa: 'قطعات موتور', nameEn: 'Engine Parts', icon: 'engine', image: '/demo/cat-engine.svg',
    description: 'واشر سرسیلندر، اویل پمپ، سوپاپ و سایر قطعات داخلی موتور.',
    children: [
      { slug: 'gaskets', nameFa: 'واشر و آب‌بندی', nameEn: 'Gaskets' },
      { slug: 'engine-internals', nameFa: 'قطعات داخلی موتور', nameEn: 'Engine Internals' },
    ],
  },
  {
    slug: 'suspension', nameFa: 'قطعات جلوبندی', nameEn: 'Suspension', icon: 'suspension', image: '/demo/cat-suspension.svg',
    description: 'کمک فنر، سیبک، طبق و بوش‌های جلوبندی.',
    children: [
      { slug: 'shock-absorbers', nameFa: 'کمک فنر', nameEn: 'Shock Absorbers' },
      { slug: 'ball-joints', nameFa: 'سیبک و طبق', nameEn: 'Ball Joints & Arms' },
    ],
  },
  {
    slug: 'electrical', nameFa: 'برق خودرو', nameEn: 'Electrical', icon: 'electrical', image: '/demo/cat-electrical.svg',
    description: 'دینام، استارت، سنسورها و رله‌های خودرو.',
    children: [
      { slug: 'alternators', nameFa: 'دینام و استارت', nameEn: 'Alternators & Starters' },
      { slug: 'sensors', nameFa: 'سنسورها', nameEn: 'Sensors' },
    ],
  },
  {
    slug: 'body', nameFa: 'قطعات بدنه', nameEn: 'Body Parts', icon: 'body', image: '/demo/cat-body.svg',
    description: 'سپر، گلگیر، چراغ و آینه برای خودروهای پرتیراژ داخلی.',
    children: [
      { slug: 'lighting', nameFa: 'چراغ و روشنایی', nameEn: 'Lighting' },
      { slug: 'panels', nameFa: 'سپر و گلگیر', nameEn: 'Bumpers & Fenders' },
    ],
  },
  {
    slug: 'lubricants', nameFa: 'روغن و روانکار', nameEn: 'Oils & Lubricants', icon: 'oil', image: '/demo/cat-oil.svg',
    description: 'روغن موتور، روغن گیربکس، ضدیخ و مایع ترمز.',
  },
  {
    slug: 'belts', nameFa: 'تسمه', nameEn: 'Belts', icon: 'belt', image: '/demo/cat-belts.svg',
    description: 'تسمه تایم، تسمه دینام و کیت کامل تسمه.',
  },
  {
    slug: 'spark-plugs', nameFa: 'شمع', nameEn: 'Spark Plugs', icon: 'plug', image: '/demo/cat-plugs.svg',
    description: 'شمع معمولی، پلاتینی و ایریدیوم.',
  },
  {
    slug: 'batteries', nameFa: 'باتری', nameEn: 'Batteries', icon: 'battery', image: '/demo/cat-battery.svg',
    description: 'باتری اسیدی و سیلد برای خودروهای سواری.',
  },
];

/* ── brands ─────────────────────────────────────────────────────────── */

const BRANDS = [
  { slug: 'bosch', nameFa: 'بوش', nameEn: 'Bosch', country: 'آلمان', description: 'برند آلمانی قطعات خودرو.' },
  { slug: 'valeo', nameFa: 'والئو', nameEn: 'Valeo', country: 'فرانسه', description: 'تأمین‌کننده فرانسوی قطعات اصلی خودرو.' },
  { slug: 'mann-filter', nameFa: 'مان فیلتر', nameEn: 'MANN-FILTER', country: 'آلمان', description: 'تخصص در فیلترهای خودرو.' },
  { slug: 'sachs', nameFa: 'زاکس', nameEn: 'SACHS', country: 'آلمان', description: 'کمک فنر و کلاچ.' },
  { slug: 'crouse', nameFa: 'کروز', nameEn: 'Crouse', country: 'ایران', description: 'تولیدکننده ایرانی قطعات برقی و موتوری خودرو.' },
  { slug: 'isaco', nameFa: 'ایساکو', nameEn: 'ISACO', country: 'ایران', description: 'شبکه تأمین قطعات ایران‌خودرو.' },
  { slug: 'saipa-yadak', nameFa: 'سایپا یدک', nameEn: 'SAIPA Yadak', country: 'ایران', description: 'شبکه تأمین قطعات سایپا.' },
  { slug: 'mahvarsazan', nameFa: 'محورسازان', nameEn: 'Mahvarsazan', country: 'ایران', description: 'قطعات جلوبندی و محور.' },
  { slug: 'behran', nameFa: 'بهران', nameEn: 'Behran Oil', country: 'ایران', description: 'روانکارهای صنعتی و خودرویی.' },
  { slug: 'sepahan-battery', nameFa: 'باتری سپاهان', nameEn: 'Sepahan Battery', country: 'ایران', description: 'باتری خودروهای سواری.' },
  { slug: 'dinaparts', nameFa: 'دینا پارت', nameEn: 'DinaParts', country: 'ایران', description: 'قطعات یدکی خودروهای داخلی.' },
];

/* ── vehicles ───────────────────────────────────────────────────────── */

const VEHICLES: {
  slug: string; nameFa: string; nameEn: string; sort: number;
  models: {
    slug: string; nameFa: string; nameEn: string; yearFrom: number; yearTo: number;
    engines: { code: string; nameFa: string; cc: number; fuel: string }[];
    generations?: { code: string; nameFa: string; yearFrom: number; yearTo: number }[];
    trims?: { code: string; nameFa: string }[];
  }[];
}[] = [
  {
    slug: 'irankhodro', nameFa: 'ایران خودرو', nameEn: 'IKCO', sort: 1,
    models: [
      { slug: 'peugeot-206', nameFa: 'پژو ۲۰۶', nameEn: 'Peugeot 206', yearFrom: 1380, yearTo: 1402,
        generations: [
          { code: 'HB', nameFa: 'هاچ‌بک', yearFrom: 1380, yearTo: 1402 },
          { code: 'SD', nameFa: 'صندوق‌دار (۲۰۶ SD)', yearFrom: 1385, yearTo: 1402 },
        ],
        trims: [
          { code: 'TIP2', nameFa: 'تیپ ۲' },
          { code: 'TIP3', nameFa: 'تیپ ۳' },
          { code: 'TIP5', nameFa: 'تیپ ۵' },
        ],
        engines: [
          { code: 'TU3', nameFa: 'موتور TU3 (۱۴۰۰ سی‌سی)', cc: 1360, fuel: 'بنزینی' },
          { code: 'TU5', nameFa: 'موتور TU5 (۱۶۰۰ سی‌سی)', cc: 1587, fuel: 'بنزینی' },
        ] },
      { slug: 'peugeot-pars', nameFa: 'پژو پارس', nameEn: 'Peugeot Pars', yearFrom: 1379, yearTo: 1403,
        engines: [
          { code: 'XU7', nameFa: 'موتور XU7 (۱۸۰۰ سی‌سی)', cc: 1761, fuel: 'بنزینی' },
          { code: 'TU5', nameFa: 'موتور TU5 (۱۶۰۰ سی‌سی)', cc: 1587, fuel: 'بنزینی' },
        ] },
      { slug: 'peugeot-405', nameFa: 'پژو ۴۰۵', nameEn: 'Peugeot 405', yearFrom: 1372, yearTo: 1399,
        engines: [{ code: 'XU7', nameFa: 'موتور XU7 (۱۸۰۰ سی‌سی)', cc: 1761, fuel: 'بنزینی' }] },
      { slug: 'samand', nameFa: 'سمند', nameEn: 'Samand', yearFrom: 1381, yearTo: 1402,
        trims: [
          { code: 'LX', nameFa: 'سمند LX' },
          { code: 'SOREN', nameFa: 'سورن' },
        ],
        engines: [
          { code: 'EF7', nameFa: 'موتور ملی EF7', cc: 1650, fuel: 'بنزینی' },
          { code: 'XU7', nameFa: 'موتور XU7 (۱۸۰۰ سی‌سی)', cc: 1761, fuel: 'بنزینی' },
        ] },
      { slug: 'dena', nameFa: 'دنا', nameEn: 'Dena', yearFrom: 1393, yearTo: 1404,
        engines: [
          { code: 'EF7', nameFa: 'موتور ملی EF7', cc: 1650, fuel: 'بنزینی' },
          { code: 'EF7-TC', nameFa: 'موتور ملی EF7 توربوشارژ', cc: 1650, fuel: 'بنزینی' },
        ] },
      { slug: 'rana', nameFa: 'رانا', nameEn: 'Runna', yearFrom: 1390, yearTo: 1403,
        engines: [{ code: 'EF7', nameFa: 'موتور ملی EF7', cc: 1650, fuel: 'بنزینی' }] },
      { slug: 'tara', nameFa: 'تارا', nameEn: 'Tara', yearFrom: 1399, yearTo: 1404,
        engines: [{ code: 'EF7-TC', nameFa: 'موتور ملی EF7 توربوشارژ', cc: 1650, fuel: 'بنزینی' }] },
    ],
  },
  {
    slug: 'saipa', nameFa: 'سایپا', nameEn: 'SAIPA', sort: 2,
    models: [
      { slug: 'pride-131', nameFa: 'پراید ۱۳۱', nameEn: 'Pride 131', yearFrom: 1387, yearTo: 1399,
        trims: [
          { code: 'SE', nameFa: 'پراید ۱۳۱ SE' },
          { code: 'SX', nameFa: 'پراید ۱۳۱ SX' },
        ],
        engines: [{ code: 'SL', nameFa: 'موتور SL (۱۳۰۰ سی‌سی)', cc: 1323, fuel: 'بنزینی' }] },
      { slug: 'tiba', nameFa: 'تیبا', nameEn: 'Tiba', yearFrom: 1388, yearTo: 1402,
        engines: [{ code: 'M13', nameFa: 'موتور M13', cc: 1329, fuel: 'بنزینی' }] },
      { slug: 'saina', nameFa: 'ساینا', nameEn: 'Saina', yearFrom: 1395, yearTo: 1403,
        engines: [{ code: 'M13', nameFa: 'موتور M13', cc: 1329, fuel: 'بنزینی' }] },
      { slug: 'quick', nameFa: 'کوییک', nameEn: 'Quick', yearFrom: 1397, yearTo: 1404,
        engines: [{ code: 'M15', nameFa: 'موتور M15', cc: 1500, fuel: 'بنزینی' }] },
      { slug: 'shahin', nameFa: 'شاهین', nameEn: 'Shahin', yearFrom: 1399, yearTo: 1404,
        engines: [{ code: 'M15', nameFa: 'موتور M15', cc: 1500, fuel: 'بنزینی' }] },
    ],
  },
  {
    slug: 'mvm', nameFa: 'مدیران خودرو', nameEn: 'MVM', sort: 3,
    models: [
      { slug: 'mvm-315', nameFa: 'ام‌وی‌ام ۳۱۵', nameEn: 'MVM 315', yearFrom: 1391, yearTo: 1398,
        engines: [{ code: 'SQR477F', nameFa: 'موتور SQR477F', cc: 1497, fuel: 'بنزینی' }] },
      { slug: 'arizo-5', nameFa: 'آریزو ۵', nameEn: 'Arrizo 5', yearFrom: 1396, yearTo: 1403,
        engines: [{ code: 'SQRE4T15', nameFa: 'موتور توربو ۱۵۰۰', cc: 1498, fuel: 'بنزینی' }] },
    ],
  },
];

/* ── products ───────────────────────────────────────────────────────── */

type Fitment = {
  model: string;
  engine?: string;
  trim?: string;
  yearFrom?: number;
  yearTo?: number;
  type?: 'DIRECT' | 'WITH_MODIFICATION' | 'NOT_COMPATIBLE';
  note?: string;
};
type Reference = {
  type: 'SUPERSEDES' | 'SUPERSEDED_BY' | 'ALTERNATE' | 'CROSS_REFERENCE';
  number: string;
  brand?: string;
};
type SeedProduct = {
  sku: string; oem: string | null; mpn: string | null; title: string; titleEn: string;
  category: string; brand: string; manufacturer: string; price: number; salePrice?: number;
  stock: number; images: string[]; weight: number; warranty: number | null; country: string;
  condition?: 'new' | 'refurbished' | 'used';
  description: string; installation?: string;
  specs: [string, string, string?][];
  fitments: Fitment[]; tags: string[];
  family?: string;
  references?: Reference[];
};

const PRODUCTS: SeedProduct[] = [
  {
    sku: 'FLT-OIL-206TU5', oem: '1109AY', mpn: 'W 712/52', title: 'فیلتر روغن پژو ۲۰۶ تیپ ۵ (موتور TU5)',
    titleEn: 'Oil Filter Peugeot 206 TU5', category: 'oil-filters', brand: 'mann-filter',
    manufacturer: 'MANN+HUMMEL', price: 385_000, salePrice: 329_000, stock: 48,
    images: ['/demo/oil-filter.svg'], weight: 260, warranty: 6, country: 'آلمان',
    description: 'فیلتر روغن اسپین‌آن با المنت کاغذی پرس‌شده و شیر یک‌طرفه سیلیکونی. مناسب موتورهای TU5 و TU3 با فاصلهٔ تعویض ۱۰٬۰۰۰ کیلومتر.',
    installation: 'پیش از بستن، واشر لاستیکی را با روغن تازه چرب کنید و فیلتر را تنها به اندازهٔ سه‌چهارم دور پس از تماس واشر سفت کنید.',
    specs: [['نوع فیلتر', 'اسپین‌آن'], ['قطر بیرونی', '۷۶', 'میلی‌متر'], ['ارتفاع', '۹۳', 'میلی‌متر'], ['رزوه', 'M20×1.5'], ['شیر یک‌طرفه', 'دارد'], ['فشار بازشدن شیر اطمینان', '۱٫۲', 'بار']],
    family: 'oil-filter-tu-series',
    fitments: [
      { model: 'peugeot-206', engine: 'TU5' },
      { model: 'peugeot-206', engine: 'TU3' },
      { model: 'peugeot-pars', engine: 'TU5' },
      { model: 'rana' },
    ],
    references: [
      { type: 'CROSS_REFERENCE', number: 'OC90', brand: 'Knecht/Mahle' },
      { type: 'CROSS_REFERENCE', number: 'PH5796', brand: 'Fram' },
      { type: 'SUPERSEDES', number: '1109N3', brand: 'Peugeot' },
    ],
    tags: ['فیلتر روغن', 'پژو', '206', 'TU5', 'oil filter'],
  },
  {
    sku: 'FLT-AIR-405XU7', oem: '1444TR', mpn: 'C 26 168', title: 'فیلتر هوا پژو ۴۰۵ و پارس (موتور XU7)',
    titleEn: 'Air Filter Peugeot 405/Pars XU7', category: 'air-filters', brand: 'mann-filter',
    manufacturer: 'MANN+HUMMEL', price: 420_000, stock: 35,
    images: ['/demo/air-filter.svg'], weight: 420, warranty: 6, country: 'آلمان',
    description: 'فیلتر هوای پانلی با کاغذ صافی چندلایه و قاب پلی‌اورتان. راندمان فیلتراسیون بالا و افت فشار پایین.',
    specs: [['نوع فیلتر', 'پانلی'], ['طول', '۲۴۰', 'میلی‌متر'], ['عرض', '۱۹۰', 'میلی‌متر'], ['ارتفاع', '۵۸', 'میلی‌متر'], ['جنس قاب', 'پلی‌اورتان']],
    fitments: [{ model: 'peugeot-405', engine: 'XU7' }, { model: 'peugeot-pars', engine: 'XU7' }, { model: 'samand', engine: 'XU7' }],
    tags: ['فیلتر هوا', 'پژو', '405', 'پارس', 'XU7', 'air filter'],
  },
  {
    sku: 'FLT-CAB-DENA', oem: '6447KJ', mpn: 'CU 2545', title: 'فیلتر کابین دنا و سمند (زغال فعال)',
    titleEn: 'Cabin Filter Dena/Samand Activated Carbon', category: 'cabin-filters', brand: 'bosch',
    manufacturer: 'Bosch', price: 510_000, salePrice: 445_000, stock: 22,
    images: ['/demo/cabin-filter.svg'], weight: 320, warranty: 6, country: 'آلمان',
    description: 'فیلتر کابین با لایهٔ زغال فعال برای حذف گرد و غبار، گرده و بوهای نامطبوع از هوای ورودی به کابین.',
    specs: [['نوع فیلتر', 'زغال فعال'], ['طول', '۲۸۵', 'میلی‌متر'], ['عرض', '۲۰۵', 'میلی‌متر'], ['ارتفاع', '۳۰', 'میلی‌متر'], ['دورهٔ تعویض', '۱۵٬۰۰۰', 'کیلومتر']],
    fitments: [{ model: 'dena' }, { model: 'samand' }, { model: 'rana' }],
    tags: ['فیلتر کابین', 'دنا', 'سمند', 'زغال فعال', 'cabin filter'],
  },
  {
    sku: 'FLT-FUEL-PRIDE', oem: '3191104000', mpn: 'WK 42/2', title: 'فیلتر بنزین پراید ۱۳۱ و تیبا',
    titleEn: 'Fuel Filter Pride 131 / Tiba', category: 'fuel-filters', brand: 'saipa-yadak',
    manufacturer: 'سایپا یدک', price: 165_000, stock: 60,
    images: ['/demo/fuel-filter.svg'], weight: 140, warranty: 3, country: 'ایران',
    description: 'فیلتر بنزین خطی با بدنهٔ فلزی و المنت کاغذی. مناسب سیستم انژکتوری خودروهای سایپا.',
    specs: [['نوع اتصال', 'خطی'], ['قطر ورودی', '۸', 'میلی‌متر'], ['فشار کاری', '۶', 'بار'], ['جنس بدنه', 'فولاد گالوانیزه']],
    fitments: [{ model: 'pride-131' }, { model: 'tiba' }, { model: 'saina' }],
    tags: ['فیلتر بنزین', 'پراید', 'تیبا', 'fuel filter'],
  },
  {
    sku: 'BRK-PAD-206F', oem: '425467', mpn: 'BP-206-F', title: 'لنت ترمز جلو پژو ۲۰۶ (تیپ ۲ تا ۵)',
    titleEn: 'Front Brake Pad Set Peugeot 206', category: 'brake-pads', brand: 'valeo',
    manufacturer: 'Valeo', price: 1_450_000, salePrice: 1_290_000, stock: 18,
    images: ['/demo/brake-pad.svg'], weight: 1_250, warranty: 12, country: 'فرانسه',
    description: 'ست کامل چهار عددی لنت ترمز جلو با ترکیب نیمه‌متالیک کم‌غبار. صدای ترمز پایین و پایداری اصطکاک در دمای بالا.',
    installation: 'پس از تعویض، پدال ترمز را چند بار پمپ کنید و ۲۰۰ کیلومتر اول را با ترمزگیری ملایم آب‌بندی کنید.',
    specs: [['تعداد در بسته', '۴', 'عدد'], ['طول', '۱۱۹', 'میلی‌متر'], ['عرض', '۵۲', 'میلی‌متر'], ['ضخامت', '۱۷', 'میلی‌متر'], ['ترکیب اصطکاکی', 'نیمه‌متالیک'], ['سنسور سایش', 'ندارد']],
    family: 'brake-pad-front-206',
    fitments: [
      { model: 'peugeot-206', yearFrom: 1382, yearTo: 1402 },
      { model: 'peugeot-206', trim: 'TIP5', engine: 'TU5' },
      { model: 'rana' },
    ],
    references: [
      { type: 'SUPERSEDES', number: '425461', brand: 'Peugeot' },
      { type: 'CROSS_REFERENCE', number: 'GDB1330', brand: 'TRW' },
      { type: 'CROSS_REFERENCE', number: '13.0460-2733.2', brand: 'ATE' },
    ],
    tags: ['لنت ترمز', 'پژو', '206', 'brake pad', 'جلو'],
  },
  {
    sku: 'BRK-PAD-PRIDE-F', oem: '5810104A00', mpn: 'BP-PR-F', title: 'لنت ترمز جلو پراید ۱۳۱',
    titleEn: 'Front Brake Pad Set Pride 131', category: 'brake-pads', brand: 'crouse',
    manufacturer: 'کروز', price: 690_000, stock: 40,
    images: ['/demo/brake-pad.svg'], weight: 1_050, warranty: 12, country: 'ایران',
    description: 'ست لنت ترمز جلو با ترکیب آلی بدون آزبست، مناسب رانندگی شهری.',
    specs: [['تعداد در بسته', '۴', 'عدد'], ['طول', '۱۰۵', 'میلی‌متر'], ['عرض', '۴۹', 'میلی‌متر'], ['ضخامت', '۱۵', 'میلی‌متر'], ['ترکیب اصطکاکی', 'آلی بدون آزبست']],
    fitments: [{ model: 'pride-131' }, { model: 'tiba' }, { model: 'saina' }],
    tags: ['لنت ترمز', 'پراید', 'تیبا', 'brake pad'],
  },
  {
    sku: 'BRK-DISC-206F', oem: '424935', mpn: 'BD-206-F', title: 'دیسک ترمز جلو پژو ۲۰۶ تیپ ۵ (جفت)',
    titleEn: 'Front Brake Disc Pair Peugeot 206 TU5', category: 'brake-discs', brand: 'bosch',
    manufacturer: 'Bosch', price: 3_850_000, stock: 9,
    images: ['/demo/brake-disc.svg'], weight: 9_800, warranty: 12, country: 'آلمان',
    description: 'جفت دیسک ترمز جلو خنک‌شونده با پوشش ضدزنگ. تلرانس بالانس دقیق برای حذف لرزش فرمان هنگام ترمزگیری.',
    specs: [['قطر', '۲۸۳', 'میلی‌متر'], ['ضخامت', '۲۶', 'میلی‌متر'], ['حداقل ضخامت مجاز', '۲۴', 'میلی‌متر'], ['تعداد پیچ', '۴'], ['نوع', 'خنک‌شونده (ونتیله)'], ['تعداد در بسته', '۲', 'عدد']],
    family: 'brake-disc-front-206',
    fitments: [
      { model: 'peugeot-206', engine: 'TU5', trim: 'TIP5' },
      { model: 'peugeot-206', engine: 'TU5' },
      { model: 'peugeot-pars', engine: 'TU5' },
      // Real-world exclusion: TU3 cars use a smaller 247mm disc.
      { model: 'peugeot-206', engine: 'TU3', type: 'NOT_COMPATIBLE',
        note: 'موتور TU3 از دیسک ۲۴۷ میلی‌متری استفاده می‌کند' },
    ],
    references: [
      { type: 'CROSS_REFERENCE', number: '4246W8', brand: 'Peugeot' },
      { type: 'ALTERNATE', number: 'DF4249' },
    ],
    tags: ['دیسک ترمز', 'پژو', '206', 'brake disc'],
  },
  {
    sku: 'SPK-PLG-EF7', oem: 'F01R00A012', mpn: 'FR7DC+', title: 'شمع موتور ملی EF7 (بستهٔ چهارتایی)',
    titleEn: 'Spark Plug Set EF7 Engine', category: 'spark-plugs', brand: 'bosch',
    manufacturer: 'Bosch', price: 980_000, salePrice: 869_000, stock: 27,
    images: ['/demo/spark-plug.svg'], weight: 260, warranty: 12, country: 'آلمان',
    description: 'شمع نیکل-ییتریوم با الکترود مرکزی مسی. دورهٔ تعویض ۲۰٬۰۰۰ کیلومتر روی موتور ملی EF7.',
    specs: [['کد حرارتی', '۷'], ['رزوه', 'M14×1.25'], ['فاصلهٔ دهانه', '۰٫۹', 'میلی‌متر'], ['گشتاور بستن', '۲۵', 'نیوتن‌متر'], ['تعداد در بسته', '۴', 'عدد']],
    family: 'spark-plug-ef7',
    fitments: [
      { model: 'dena', engine: 'EF7' },
      { model: 'samand', engine: 'EF7', trim: 'SOREN' },
      { model: 'samand', engine: 'EF7', trim: 'LX' },
      { model: 'rana', engine: 'EF7' },
    ],
    references: [
      { type: 'CROSS_REFERENCE', number: 'FR7DC+', brand: 'Bosch' },
      { type: 'ALTERNATE', number: 'BKR6E-11', brand: 'NGK' },
    ],
    tags: ['شمع', 'EF7', 'موتور ملی', 'spark plug', 'دنا', 'سمند'],
  },
  {
    sku: 'SPK-PLG-TU5', oem: '5960F7', mpn: 'FR8DC', title: 'شمع پژو ۲۰۶ موتور TU5 (بستهٔ چهارتایی)',
    titleEn: 'Spark Plug Set Peugeot 206 TU5', category: 'spark-plugs', brand: 'valeo',
    manufacturer: 'Valeo', price: 720_000, stock: 33,
    images: ['/demo/spark-plug.svg'], weight: 250, warranty: 12, country: 'فرانسه',
    description: 'شمع استاندارد با الکترود نیکلی، مطابق مشخصات کارخانه‌ای موتورهای TU.',
    specs: [['کد حرارتی', '۸'], ['رزوه', 'M14×1.25'], ['فاصلهٔ دهانه', '۰٫۸', 'میلی‌متر'], ['تعداد در بسته', '۴', 'عدد']],
    fitments: [{ model: 'peugeot-206', engine: 'TU5' }, { model: 'peugeot-206', engine: 'TU3' }, { model: 'peugeot-pars', engine: 'TU5' }],
    tags: ['شمع', 'TU5', 'پژو', '206', 'spark plug'],
  },
  {
    sku: 'BAT-60AH-R', oem: null, mpn: 'SP-60R', title: 'باتری ۶۰ آمپر ساعت سپاهان (قطب راست)',
    titleEn: 'Car Battery 60Ah Right Terminal', category: 'batteries', brand: 'sepahan-battery',
    manufacturer: 'باتری سپاهان', price: 4_950_000, salePrice: 4_590_000, stock: 12,
    images: ['/demo/battery.svg'], weight: 15_500, warranty: 18, country: 'ایران',
    description: 'باتری سرب-اسیدی کم‌نگهداری با جریان راه‌اندازی سرد ۵۴۰ آمپر. مناسب خودروهای سواری با موتور تا ۲۰۰۰ سی‌سی.',
    installation: 'هنگام نصب ابتدا قطب مثبت و سپس منفی را وصل کنید؛ هنگام باز کردن ترتیب معکوس را رعایت کنید.',
    specs: [['ظرفیت', '۶۰', 'آمپرساعت'], ['ولتاژ', '۱۲', 'ولت'], ['جریان راه‌اندازی سرد (CCA)', '۵۴۰', 'آمپر'], ['قطب مثبت', 'سمت راست'], ['طول', '۲۴۲', 'میلی‌متر'], ['عرض', '۱۷۵', 'میلی‌متر'], ['ارتفاع', '۱۹۰', 'میلی‌متر']],
    fitments: [{ model: 'peugeot-206' }, { model: 'peugeot-pars' }, { model: 'samand' }, { model: 'dena' }, { model: 'tiba' }, { model: 'quick' }],
    tags: ['باتری', '۶۰ آمپر', 'سپاهان', 'battery'],
  },
  {
    sku: 'BAT-66AH-L', oem: null, mpn: 'SP-66L', title: 'باتری ۶۶ آمپر ساعت سپاهان (قطب چپ)',
    titleEn: 'Car Battery 66Ah Left Terminal', category: 'batteries', brand: 'sepahan-battery',
    manufacturer: 'باتری سپاهان', price: 5_450_000, stock: 7,
    images: ['/demo/battery.svg'], weight: 17_200, warranty: 18, country: 'ایران',
    description: 'باتری سرب-اسیدی با ظرفیت بالاتر برای خودروهای دارای مصرف‌کننده‌های جانبی زیاد.',
    specs: [['ظرفیت', '۶۶', 'آمپرساعت'], ['ولتاژ', '۱۲', 'ولت'], ['جریان راه‌اندازی سرد (CCA)', '۶۰۰', 'آمپر'], ['قطب مثبت', 'سمت چپ']],
    fitments: [{ model: 'dena' }, { model: 'tara' }, { model: 'shahin' }, { model: 'arizo-5' }],
    tags: ['باتری', '۶۶ آمپر', 'battery'],
  },
  {
    sku: 'BLT-TIM-EF7', oem: '0829F3', mpn: 'TB-EF7-KIT', title: 'کیت تسمه تایم موتور ملی EF7',
    titleEn: 'Timing Belt Kit EF7', category: 'belts', brand: 'crouse',
    manufacturer: 'کروز', price: 2_650_000, stock: 14,
    images: ['/demo/timing-belt.svg'], weight: 1_800, warranty: 12, country: 'ایران',
    description: 'کیت کامل شامل تسمه تایم دندانه‌دار، تسمه‌سفت‌کن و هرزگرد. دورهٔ تعویض توصیه‌شده ۶۰٬۰۰۰ کیلومتر.',
    installation: 'تعویض تسمه تایم نیازمند تنظیم دقیق تایمینگ است و باید توسط تعمیرکار مجرب انجام شود.',
    specs: [['تعداد دندانه', '۱۳۷'], ['عرض تسمه', '۲۵٫۴', 'میلی‌متر'], ['محتویات بسته', 'تسمه + سفت‌کن + هرزگرد'], ['دورهٔ تعویض', '۶۰٬۰۰۰', 'کیلومتر']],
    fitments: [{ model: 'dena', engine: 'EF7' }, { model: 'samand', engine: 'EF7' }, { model: 'rana', engine: 'EF7' }],
    tags: ['تسمه تایم', 'EF7', 'کیت', 'timing belt'],
  },
  {
    sku: 'BLT-ALT-XU7', oem: '5750WK', mpn: '6PK1123', title: 'تسمه دینام پژو ۴۰۵ و پارس (XU7)',
    titleEn: 'Alternator Belt Peugeot 405/Pars', category: 'belts', brand: 'dinaparts',
    manufacturer: 'دینا پارت', price: 480_000, stock: 46,
    images: ['/demo/v-belt.svg'], weight: 320, warranty: 6, country: 'ایران',
    description: 'تسمه شیاردار شش‌شیاره با هستهٔ پلی‌استر و روکش مقاوم در برابر روغن و حرارت.',
    specs: [['تعداد شیار', '۶'], ['طول', '۱۱۲۳', 'میلی‌متر'], ['نوع', 'پلی‌وی (PK)']],
    fitments: [{ model: 'peugeot-405', engine: 'XU7' }, { model: 'peugeot-pars', engine: 'XU7' }, { model: 'samand', engine: 'XU7' }],
    tags: ['تسمه دینام', 'پژو', 'XU7', 'belt'],
  },
  {
    sku: 'SUS-SHK-206F', oem: '5202GH', mpn: 'SA-206-F', title: 'کمک فنر جلو پژو ۲۰۶ (روغنی، عدد)',
    titleEn: 'Front Shock Absorber Peugeot 206', category: 'shock-absorbers', brand: 'sachs',
    manufacturer: 'SACHS', price: 2_950_000, salePrice: 2_690_000, stock: 16,
    images: ['/demo/shock-absorber.svg'], weight: 3_400, warranty: 12, country: 'آلمان',
    description: 'کمک فنر تلسکوپی روغنی جلو با میل‌پیستون کروم‌اندود. قیمت به ازای یک عدد است؛ تعویض جفتی توصیه می‌شود.',
    installation: 'کمک فنرهای چپ و راست را همزمان تعویض کنید تا رفتار تعلیق متقارن بماند.',
    specs: [['نوع', 'روغنی (هیدرولیک)'], ['موقعیت نصب', 'محور جلو'], ['طول بسته', '۳۶۵', 'میلی‌متر'], ['طول باز', '۵۵۵', 'میلی‌متر'], ['تعداد در بسته', '۱', 'عدد']],
    fitments: [{ model: 'peugeot-206' }, { model: 'rana' }],
    tags: ['کمک فنر', 'پژو', '206', 'جلوبندی', 'shock absorber'],
  },
  {
    sku: 'SUS-BJ-PARS', oem: '3520N1', mpn: 'BJ-PARS', title: 'سیبک طبق پژو پارس و ۴۰۵',
    titleEn: 'Lower Ball Joint Peugeot Pars/405', category: 'ball-joints', brand: 'mahvarsazan',
    manufacturer: 'محورسازان', price: 620_000, stock: 38,
    images: ['/demo/ball-joint.svg'], weight: 640, warranty: 12, country: 'ایران',
    description: 'سیبک طبق با بدنهٔ فورج‌شده و گردگیر نئوپرن مقاوم در برابر گرد و غبار.',
    specs: [['قطر مخروط', '۱۷', 'میلی‌متر'], ['رزوه', 'M12×1.25'], ['جنس بدنه', 'فولاد فورج'], ['جنس گردگیر', 'نئوپرن']],
    fitments: [{ model: 'peugeot-pars' }, { model: 'peugeot-405' }, { model: 'samand' }],
    tags: ['سیبک', 'جلوبندی', 'پژو', 'پارس', 'ball joint'],
  },
  {
    sku: 'ENG-GSK-XU7', oem: '0209S8', mpn: 'HG-XU7', title: 'واشر سرسیلندر پژو ۴۰۵ و پارس (XU7)',
    titleEn: 'Cylinder Head Gasket XU7', category: 'gaskets', brand: 'isaco',
    manufacturer: 'ایساکو', price: 1_180_000, stock: 21,
    images: ['/demo/engine-part.svg'], weight: 480, warranty: 6, country: 'ایران',
    description: 'واشر سرسیلندر چندلایه فلزی (MLS) با آب‌بندی الاستومری اطراف مجاری روغن و آب.',
    installation: 'گشتاور پیچ‌های سرسیلندر باید مطابق دستورالعمل کارخانه و به‌صورت مرحله‌ای اعمال شود.',
    specs: [['نوع', 'چندلایه فلزی (MLS)'], ['تعداد سیلندر', '۴'], ['ضخامت', '۱٫۲', 'میلی‌متر'], ['قطر سیلندر', '۸۳', 'میلی‌متر']],
    fitments: [{ model: 'peugeot-405', engine: 'XU7' }, { model: 'peugeot-pars', engine: 'XU7' }, { model: 'samand', engine: 'XU7' }],
    tags: ['واشر سرسیلندر', 'XU7', 'موتور', 'gasket'],
  },
  {
    sku: 'ENG-OILP-EF7', oem: '0827K1', mpn: 'OP-EF7', title: 'اویل پمپ موتور ملی EF7',
    titleEn: 'Oil Pump EF7 Engine', category: 'engine-internals', brand: 'crouse',
    manufacturer: 'کروز', price: 3_450_000, stock: 6,
    images: ['/demo/engine-part.svg'], weight: 2_100, warranty: 12, country: 'ایران',
    description: 'اویل پمپ دنده‌ای با شیر تنظیم فشار. تأمین‌کنندهٔ روانکاری مجموعهٔ متحرک موتور ملی.',
    specs: [['نوع', 'دنده‌ای (Gerotor)'], ['فشار کاری', '۳٫۵', 'بار'], ['دبی در ۳۰۰۰ دور', '۳۲', 'لیتر بر دقیقه']],
    fitments: [{ model: 'dena', engine: 'EF7' }, { model: 'samand', engine: 'EF7' }, { model: 'rana', engine: 'EF7' }, { model: 'tara', engine: 'EF7-TC' }],
    tags: ['اویل پمپ', 'EF7', 'موتور ملی', 'oil pump'],
  },
  {
    sku: 'ELC-ALT-SAM', oem: '1147MK', mpn: 'ALT-SAM-90', title: 'دینام سمند و پژو پارس (۹۰ آمپر)',
    titleEn: 'Alternator Samand/Pars 90A', category: 'alternators', brand: 'crouse',
    manufacturer: 'کروز', price: 8_900_000, salePrice: 8_250_000, stock: 5,
    images: ['/demo/alternator.svg'], weight: 5_600, warranty: 12, country: 'ایران',
    description: 'دینام ۹۰ آمپر با رگولاتور داخلی و پولی هرزگرد یک‌طرفه. سازگار با سیستم برق ۱۲ ولت خودروهای ایران‌خودرو.',
    specs: [['جریان خروجی', '۹۰', 'آمپر'], ['ولتاژ', '۱۲', 'ولت'], ['تعداد شیار پولی', '۶'], ['نوع پولی', 'یک‌طرفه (OAP)'], ['جهت چرخش', 'ساعتگرد']],
    fitments: [{ model: 'samand' }, { model: 'peugeot-pars' }, { model: 'dena' }],
    tags: ['دینام', 'برق خودرو', 'سمند', 'پارس', 'alternator'],
  },
  {
    sku: 'ELC-SNS-O2-TU5', oem: '1618JQ', mpn: 'LSU-4.2', title: 'سنسور اکسیژن پژو ۲۰۶ (TU5)',
    titleEn: 'Oxygen Sensor Peugeot 206 TU5', category: 'sensors', brand: 'bosch',
    manufacturer: 'Bosch', price: 2_380_000, stock: 11,
    images: ['/demo/alternator.svg'], weight: 180, warranty: 12, country: 'آلمان',
    description: 'سنسور اکسیژن پهن‌باند چهارسیمه با گرمکن داخلی. نصب پیش از کاتالیست.',
    specs: [['تعداد سیم', '۴'], ['موقعیت', 'قبل از کاتالیست'], ['طول کابل', '۵۵۰', 'میلی‌متر'], ['رزوه', 'M18×1.5']],
    fitments: [{ model: 'peugeot-206', engine: 'TU5' }, { model: 'peugeot-pars', engine: 'TU5' }],
    tags: ['سنسور اکسیژن', 'O2', 'پژو', 'sensor'],
  },
  {
    sku: 'BDY-HL-PRIDE-R', oem: '9210260B00', mpn: 'HL-PR-R', title: 'چراغ جلو راست پراید ۱۳۱',
    titleEn: 'Right Headlight Pride 131', category: 'lighting', brand: 'saipa-yadak',
    manufacturer: 'سایپا یدک', price: 2_150_000, stock: 8,
    images: ['/demo/headlight.svg'], weight: 2_400, warranty: 6, country: 'ایران',
    description: 'چراغ جلو سمت راست با کاسهٔ بازتاب کروم و لنز پلی‌کربنات مقاوم در برابر UV. بدون لامپ.',
    specs: [['سمت نصب', 'راست (شاگرد)'], ['نوع لامپ', 'H4'], ['جنس لنز', 'پلی‌کربنات'], ['تنظیم ارتفاع', 'دستی'], ['لامپ همراه', 'ندارد']],
    fitments: [{ model: 'pride-131', yearFrom: 1387, yearTo: 1399 }],
    tags: ['چراغ جلو', 'پراید', 'بدنه', 'headlight'],
  },
  {
    sku: 'BDY-FEN-206-L', oem: '7841L4', mpn: 'FEN-206-L', title: 'گلگیر جلو چپ پژو ۲۰۶',
    titleEn: 'Front Left Fender Peugeot 206', category: 'panels', brand: 'isaco',
    manufacturer: 'ایساکو', price: 3_250_000, stock: 4,
    images: ['/demo/body-panel.svg'], weight: 4_800, warranty: 6, country: 'ایران',
    description: 'گلگیر جلو سمت چپ از ورق فولادی گالوانیزه با پوشش الکترواستاتیک آستری. آمادهٔ رنگ‌آمیزی.',
    specs: [['سمت نصب', 'چپ (راننده)'], ['جنس', 'فولاد گالوانیزه'], ['ضخامت ورق', '۰٫۷', 'میلی‌متر'], ['وضعیت رنگ', 'آستری (نیازمند رنگ)']],
    fitments: [{ model: 'peugeot-206' }],
    tags: ['گلگیر', 'بدنه', 'پژو', '206', 'fender'],
  },
  {
    sku: 'LUB-ENG-10W40-4L', oem: null, mpn: 'BHR-10W40-4', title: 'روغن موتور بهران ۱۰W-۴۰ نیمه‌سینتتیک (۴ لیتری)',
    titleEn: 'Engine Oil 10W-40 Semi-Synthetic 4L', category: 'lubricants', brand: 'behran',
    manufacturer: 'نفت بهران', price: 1_380_000, salePrice: 1_190_000, stock: 55,
    images: ['/demo/motor-oil.svg'], weight: 3_900, warranty: null, country: 'ایران',
    description: 'روغن موتور نیمه‌سینتتیک چنددرجه‌ای برای موتورهای بنزینی. دورهٔ تعویض تا ۸٬۰۰۰ کیلومتر.',
    specs: [['گرانروی (SAE)', '10W-40'], ['سطح کیفیت (API)', 'SN'], ['حجم', '۴', 'لیتر'], ['پایه', 'نیمه‌سینتتیک'], ['دورهٔ تعویض', '۸٬۰۰۰', 'کیلومتر']],
    fitments: [{ model: 'peugeot-206' }, { model: 'peugeot-pars' }, { model: 'samand' }, { model: 'dena' }, { model: 'pride-131' }, { model: 'tiba' }, { model: 'quick' }],
    tags: ['روغن موتور', 'بهران', '10W40', 'engine oil'],
  },
  {
    sku: 'LUB-GEAR-75W90-1L', oem: null, mpn: 'BHR-75W90-1', title: 'روغن گیربکس بهران ۷۵W-۹۰ (۱ لیتری)',
    titleEn: 'Gear Oil 75W-90 1L', category: 'lubricants', brand: 'behran',
    manufacturer: 'نفت بهران', price: 690_000, stock: 42,
    images: ['/demo/gear-oil.svg'], weight: 1_000, warranty: null, country: 'ایران',
    description: 'روغن دنده سنتتیک با سطح کیفیت GL-4 برای گیربکس‌های دستی خودروهای سواری.',
    specs: [['گرانروی (SAE)', '75W-90'], ['سطح کیفیت (API)', 'GL-4'], ['حجم', '۱', 'لیتر'], ['پایه', 'سینتتیک']],
    fitments: [{ model: 'peugeot-206' }, { model: 'samand' }, { model: 'tiba' }, { model: 'quick' }],
    tags: ['روغن گیربکس', 'بهران', '75W90', 'gear oil'],
  },
  {
    sku: 'FLT-OIL-PRIDE', oem: '2630002501', mpn: 'W 610/3', title: 'فیلتر روغن پراید و تیبا',
    titleEn: 'Oil Filter Pride / Tiba', category: 'oil-filters', brand: 'saipa-yadak',
    manufacturer: 'سایپا یدک', price: 145_000, stock: 88,
    images: ['/demo/oil-filter.svg'], weight: 210, warranty: 3, country: 'ایران',
    description: 'فیلتر روغن اسپین‌آن مناسب موتورهای SL و M13 خانوادهٔ سایپا.',
    specs: [['نوع فیلتر', 'اسپین‌آن'], ['قطر بیرونی', '۶۸', 'میلی‌متر'], ['ارتفاع', '۷۵', 'میلی‌متر'], ['رزوه', 'M20×1.5']],
    fitments: [{ model: 'pride-131' }, { model: 'tiba' }, { model: 'saina' }, { model: 'quick' }],
    tags: ['فیلتر روغن', 'پراید', 'تیبا', 'oil filter'],
  },
  {
    sku: 'BRK-PAD-QUICK-F', oem: '5810107A10', mpn: 'BP-QK-F', title: 'لنت ترمز جلو کوییک و ساینا',
    titleEn: 'Front Brake Pads Quick / Saina', category: 'brake-pads', brand: 'crouse',
    manufacturer: 'کروز', price: 810_000, stock: 2,
    images: ['/demo/brake-pad.svg'], weight: 1_100, warranty: 12, country: 'ایران',
    description: 'ست لنت ترمز جلو با ترکیب سرامیکی کم‌غبار و صدای پایین.',
    specs: [['تعداد در بسته', '۴', 'عدد'], ['طول', '۱۱۰', 'میلی‌متر'], ['عرض', '۵۰', 'میلی‌متر'], ['ضخامت', '۱۶', 'میلی‌متر'], ['ترکیب اصطکاکی', 'سرامیکی']],
    fitments: [{ model: 'quick' }, { model: 'saina' }, { model: 'shahin' }],
    tags: ['لنت ترمز', 'کوییک', 'ساینا', 'brake pad'],
  },
  {
    sku: 'SUS-SHK-PRIDE-R', oem: '5530104000', mpn: 'SA-PR-R', title: 'کمک فنر عقب پراید ۱۳۱ (عدد)',
    titleEn: 'Rear Shock Absorber Pride 131', category: 'shock-absorbers', brand: 'mahvarsazan',
    manufacturer: 'محورسازان', price: 1_150_000, stock: 24,
    images: ['/demo/shock-absorber.svg'], weight: 2_300, warranty: 12, country: 'ایران',
    description: 'کمک فنر عقب روغنی با بوش‌های لاستیکی. قیمت به ازای یک عدد.',
    specs: [['نوع', 'روغنی'], ['موقعیت نصب', 'محور عقب'], ['طول بسته', '۲۹۰', 'میلی‌متر'], ['طول باز', '۴۵۰', 'میلی‌متر'], ['تعداد در بسته', '۱', 'عدد']],
    fitments: [{ model: 'pride-131' }, { model: 'tiba' }],
    tags: ['کمک فنر', 'پراید', 'عقب', 'shock absorber'],
  },
  {
    sku: 'FLT-AIR-QUICK', oem: '2811304000', mpn: 'C 22 011', title: 'فیلتر هوا کوییک، ساینا و تیبا',
    titleEn: 'Air Filter Quick / Saina / Tiba', category: 'air-filters', brand: 'saipa-yadak',
    manufacturer: 'سایپا یدک', price: 285_000, stock: 0,
    images: ['/demo/air-filter.svg'], weight: 350, warranty: 3, country: 'ایران',
    description: 'فیلتر هوای پانلی مناسب موتورهای M13 و M15 خانوادهٔ سایپا.',
    specs: [['نوع فیلتر', 'پانلی'], ['طول', '۲۲۵', 'میلی‌متر'], ['عرض', '۱۷۰', 'میلی‌متر'], ['ارتفاع', '۵۰', 'میلی‌متر']],
    fitments: [{ model: 'quick' }, { model: 'saina' }, { model: 'tiba' }],
    tags: ['فیلتر هوا', 'کوییک', 'ساینا', 'تیبا', 'air filter'],
  },
  {
    sku: 'ENG-GSK-TU5', oem: '0209T5', mpn: 'HG-TU5', title: 'واشر سرسیلندر پژو ۲۰۶ تیپ ۵ (TU5)',
    titleEn: 'Cylinder Head Gasket TU5', category: 'gaskets', brand: 'isaco',
    manufacturer: 'ایساکو', price: 980_000, stock: 17,
    images: ['/demo/engine-part.svg'], weight: 380, warranty: 6, country: 'ایران',
    description: 'واشر سرسیلندر چندلایه فلزی مخصوص موتورهای TU5 با آب‌بندی مجاری روغن.',
    specs: [['نوع', 'چندلایه فلزی (MLS)'], ['تعداد سیلندر', '۴'], ['ضخامت', '۱٫۱', 'میلی‌متر'], ['قطر سیلندر', '۷۸٫۵', 'میلی‌متر']],
    fitments: [{ model: 'peugeot-206', engine: 'TU5' }, { model: 'peugeot-pars', engine: 'TU5' }],
    tags: ['واشر سرسیلندر', 'TU5', 'موتور', 'gasket'],
  },
  {
    sku: 'BDY-HL-206-L', oem: '6205AK', mpn: 'HL-206-L', title: 'چراغ جلو چپ پژو ۲۰۶',
    titleEn: 'Left Headlight Peugeot 206', category: 'lighting', brand: 'isaco',
    manufacturer: 'ایساکو', price: 2_890_000, stock: 6,
    images: ['/demo/headlight.svg'], weight: 2_600, warranty: 6, country: 'ایران',
    description: 'چراغ جلو سمت چپ با لنز شفاف و بازتاب چندکاسه‌ای. بدون لامپ.',
    specs: [['سمت نصب', 'چپ (راننده)'], ['نوع لامپ', 'H7 + H1'], ['جنس لنز', 'پلی‌کربنات'], ['تنظیم ارتفاع', 'برقی'], ['لامپ همراه', 'ندارد']],
    fitments: [{ model: 'peugeot-206' }],
    tags: ['چراغ جلو', 'پژو', '206', 'بدنه', 'headlight'],
  },
  {
    sku: 'ELC-ALT-PRIDE', oem: '3730002550', mpn: 'ALT-PR-65', title: 'دینام پراید ۱۳۱ (۶۵ آمپر)',
    titleEn: 'Alternator Pride 131 65A', category: 'alternators', brand: 'crouse',
    manufacturer: 'کروز', price: 5_600_000, stock: 3,
    images: ['/demo/alternator.svg'], weight: 4_800, warranty: 12, country: 'ایران',
    description: 'دینام ۶۵ آمپر با رگولاتور داخلی، سازگار با سیستم برق خودروهای سایپا.',
    specs: [['جریان خروجی', '۶۵', 'آمپر'], ['ولتاژ', '۱۲', 'ولت'], ['تعداد شیار پولی', '۴'], ['جهت چرخش', 'ساعتگرد']],
    fitments: [{ model: 'pride-131' }, { model: 'tiba' }],
    tags: ['دینام', 'پراید', 'برق خودرو', 'alternator'],
  },
  {
    sku: 'SUS-BJ-206', oem: '3523E5', mpn: 'BJ-206', title: 'سیبک طبق پژو ۲۰۶',
    titleEn: 'Lower Ball Joint Peugeot 206', category: 'ball-joints', brand: 'mahvarsazan',
    manufacturer: 'محورسازان', price: 540_000, stock: 31,
    images: ['/demo/ball-joint.svg'], weight: 560, warranty: 12, country: 'ایران',
    description: 'سیبک طبق پایین با گردگیر مقاوم و روانکاری مادام‌العمر.',
    specs: [['قطر مخروط', '۱۶', 'میلی‌متر'], ['رزوه', 'M12×1.25'], ['جنس بدنه', 'فولاد فورج']],
    fitments: [{ model: 'peugeot-206' }, { model: 'rana' }],
    tags: ['سیبک', 'جلوبندی', 'پژو', '206', 'ball joint'],
  },
  {
    sku: 'BRK-DISC-PRIDE-F', oem: '5171104000', mpn: 'BD-PR-F', title: 'دیسک ترمز جلو پراید ۱۳۱ (جفت)',
    titleEn: 'Front Brake Discs Pride 131 Pair', category: 'brake-discs', brand: 'crouse',
    manufacturer: 'کروز', price: 1_750_000, stock: 13,
    images: ['/demo/brake-disc.svg'], weight: 7_200, warranty: 12, country: 'ایران',
    description: 'جفت دیسک ترمز جلو توپر با پوشش ضدزنگ.',
    specs: [['قطر', '۲۳۴', 'میلی‌متر'], ['ضخامت', '۱۸', 'میلی‌متر'], ['حداقل ضخامت مجاز', '۱۶', 'میلی‌متر'], ['تعداد پیچ', '۴'], ['نوع', 'توپر'], ['تعداد در بسته', '۲', 'عدد']],
    fitments: [{ model: 'pride-131' }, { model: 'tiba' }],
    tags: ['دیسک ترمز', 'پراید', 'brake disc'],
  },
  /*
   * The block below deepens coverage for the two highest-volume Iranian
   * platforms so that a few (category × vehicle) pairings genuinely clear the
   * landing-page indexability threshold. Real catalogues carry several brands
   * per fitment; a demo with one part per pairing would make the curated-page
   * logic untestable.
   */
  {
    sku: 'BRK-PAD-206F-ECO', oem: '425235', mpn: 'BP-206-F-E', title: 'لنت ترمز جلو پژو ۲۰۶ (سری اقتصادی)',
    titleEn: 'Front Brake Pad Set Peugeot 206 Economy', category: 'brake-pads', brand: 'saipa-yadak',
    manufacturer: 'سایپا یدک', price: 890_000, stock: 26,
    images: ['/demo/brake-pad.svg'], weight: 1_180, warranty: 6, country: 'ایران',
    description: 'ست چهار عددی لنت ترمز جلو با ترکیب آلی بدون آزبست. گزینهٔ اقتصادی برای رانندگی شهری با ترمزگیری متعارف.',
    installation: 'صفحات ضدصدا را در جای خود قرار دهید و پیچ کالیپر را با گشتاور ۳۰ نیوتون‌متر ببندید.',
    specs: [['تعداد در بسته', '۴', 'عدد'], ['طول', '۱۱۹', 'میلی‌متر'], ['عرض', '۵۲', 'میلی‌متر'], ['ضخامت', '۱۷', 'میلی‌متر'], ['ترکیب اصطکاکی', 'آلی بدون آزبست'], ['سنسور سایش', 'ندارد']],
    family: 'brake-pad-front-206',
    fitments: [
      { model: 'peugeot-206', yearFrom: 1382, yearTo: 1402 },
      { model: 'rana' },
    ],
    references: [
      { type: 'ALTERNATE', number: '425467', brand: 'Peugeot' },
      { type: 'CROSS_REFERENCE', number: 'GDB1330', brand: 'TRW' },
    ],
    tags: ['لنت ترمز', 'پژو', '206', 'brake pad', 'اقتصادی'],
  },
  {
    sku: 'BRK-PAD-206R', oem: '425470', mpn: 'BP-206-R', title: 'لنت ترمز عقب پژو ۲۰۶ و رانا',
    titleEn: 'Rear Brake Pad Set Peugeot 206 / Runna', category: 'brake-pads', brand: 'valeo',
    manufacturer: 'Valeo', price: 1_180_000, stock: 14,
    images: ['/demo/brake-pad.svg'], weight: 980, warranty: 12, country: 'فرانسه',
    description: 'ست لنت ترمز عقب برای خودروهای مجهز به ترمز دیسکی عقب. ترکیب کم‌غبار با پایداری اصطکاک در ترمزگیری پی‌درپی.',
    specs: [['تعداد در بسته', '۴', 'عدد'], ['طول', '۸۷', 'میلی‌متر'], ['عرض', '۵۳', 'میلی‌متر'], ['ضخامت', '۱۵', 'میلی‌متر'], ['ترکیب اصطکاکی', 'نیمه‌متالیک']],
    family: 'brake-pad-rear-206',
    fitments: [
      { model: 'peugeot-206', trim: 'TIP5' },
      { model: 'rana' },
    ],
    references: [{ type: 'CROSS_REFERENCE', number: 'GDB1621', brand: 'TRW' }],
    tags: ['لنت ترمز', 'عقب', 'پژو', '206', 'رانا'],
  },
  {
    sku: 'FLT-AIR-206TU5', oem: '1444QT', mpn: 'C 25 114', title: 'فیلتر هوا پژو ۲۰۶ و رانا (موتور TU5)',
    titleEn: 'Air Filter Peugeot 206 / Runna TU5', category: 'air-filters', brand: 'mann-filter',
    manufacturer: 'MANN+HUMMEL', price: 395_000, stock: 40,
    images: ['/demo/air-filter.svg'], weight: 380, warranty: 6, country: 'آلمان',
    description: 'فیلتر هوای پانلی با کاغذ صافی رزین‌اندود و قاب پلی‌اورتان یکپارچه. آب‌بندی کامل در محفظهٔ فیلتر و افت فشار پایین.',
    specs: [['نوع فیلتر', 'پانلی'], ['طول', '۲۵۲', 'میلی‌متر'], ['عرض', '۱۸۶', 'میلی‌متر'], ['ارتفاع', '۵۲', 'میلی‌متر'], ['جنس قاب', 'پلی‌اورتان']],
    family: 'air-filter-tu-series',
    fitments: [
      { model: 'peugeot-206', engine: 'TU5' },
      { model: 'peugeot-206', engine: 'TU3' },
      { model: 'rana' },
    ],
    references: [{ type: 'CROSS_REFERENCE', number: 'LX 1566', brand: 'Knecht/Mahle' }],
    tags: ['فیلتر هوا', 'پژو', '206', 'رانا', 'air filter'],
  },
  {
    sku: 'FLT-OIL-206-ISACO', oem: '1109AH', mpn: 'OF-206-IS', title: 'فیلتر روغن پژو ۲۰۶ (تولید داخل)',
    titleEn: 'Oil Filter Peugeot 206 Domestic', category: 'oil-filters', brand: 'isaco',
    manufacturer: 'ایساکو', price: 178_000, stock: 60,
    images: ['/demo/oil-filter.svg'], weight: 250, warranty: 3, country: 'ایران',
    description: 'فیلتر روغن اسپین‌آن تولید داخل با المنت کاغذی و شیر یک‌طرفه لاستیکی. گزینهٔ اقتصادی برای سرویس دوره‌ای.',
    specs: [['نوع فیلتر', 'اسپین‌آن'], ['قطر بیرونی', '۷۶', 'میلی‌متر'], ['ارتفاع', '۹۰', 'میلی‌متر'], ['رزوه', 'M20×1.5'], ['شیر یک‌طرفه', 'دارد']],
    family: 'oil-filter-tu-series',
    fitments: [
      { model: 'peugeot-206' },
      { model: 'peugeot-pars', engine: 'TU5' },
      { model: 'rana' },
    ],
    references: [{ type: 'ALTERNATE', number: '1109AY', brand: 'Peugeot' }],
    tags: ['فیلتر روغن', 'پژو', '206', 'ایساکو'],
  },
  {
    sku: 'FLT-CAB-206', oem: '6447KL', mpn: 'CU 2882', title: 'فیلتر کابین پژو ۲۰۶ و پارس',
    titleEn: 'Cabin Filter Peugeot 206 / Pars', category: 'cabin-filters', brand: 'bosch',
    manufacturer: 'Bosch', price: 430_000, stock: 30,
    images: ['/demo/cabin-filter.svg'], weight: 290, warranty: 6, country: 'آلمان',
    description: 'فیلتر کابین ذره‌ای برای حذف گرد و غبار و گرده از هوای ورودی به کابین. تعویض دوره‌ای بوی نامطبوع سیستم تهویه را کاهش می‌دهد.',
    specs: [['نوع فیلتر', 'ذره‌ای'], ['طول', '۲۸۰', 'میلی‌متر'], ['عرض', '۲۰۶', 'میلی‌متر'], ['ارتفاع', '۲۰', 'میلی‌متر'], ['دورهٔ تعویض', '۱۵٬۰۰۰', 'کیلومتر']],
    fitments: [
      { model: 'peugeot-206' },
      { model: 'peugeot-pars' },
      { model: 'rana' },
    ],
    tags: ['فیلتر کابین', 'پژو', '206', 'پارس'],
  },
  {
    sku: 'BRK-PAD-TIBA-F', oem: '58101-4A000', mpn: 'BP-TIBA-F', title: 'لنت ترمز جلو تیبا و ساینا',
    titleEn: 'Front Brake Pad Set Tiba / Saina', category: 'brake-pads', brand: 'saipa-yadak',
    manufacturer: 'سایپا یدک', price: 820_000, stock: 24,
    images: ['/demo/brake-pad.svg'], weight: 1_050, warranty: 6, country: 'ایران',
    description: 'ست چهار عددی لنت ترمز جلو با ترکیب آلی. مناسب کالیپر تک‌پیستونهٔ خانوادهٔ تیبا.',
    specs: [['تعداد در بسته', '۴', 'عدد'], ['طول', '۱۰۵', 'میلی‌متر'], ['عرض', '۴۹', 'میلی‌متر'], ['ضخامت', '۱۶', 'میلی‌متر'], ['ترکیب اصطکاکی', 'آلی بدون آزبست']],
    family: 'brake-pad-front-pride',
    fitments: [
      { model: 'tiba' },
      { model: 'saina' },
      { model: 'quick' },
    ],
    references: [{ type: 'ALTERNATE', number: 'PB-131-F', brand: 'SAIPA' }],
    tags: ['لنت ترمز', 'تیبا', 'ساینا', 'کوییک'],
  },
  {
    sku: 'FLT-AIR-PRIDE', oem: '28113-4A000', mpn: 'C 20 114', title: 'فیلتر هوا پراید، تیبا و ساینا',
    titleEn: 'Air Filter Pride / Tiba / Saina', category: 'air-filters', brand: 'mann-filter',
    manufacturer: 'MANN+HUMMEL', price: 285_000, stock: 52,
    images: ['/demo/air-filter.svg'], weight: 300, warranty: 6, country: 'آلمان',
    description: 'فیلتر هوای پانلی با کاغذ صافی چندلایه. مناسب موتورهای خانوادهٔ پراید با فاصلهٔ تعویض ۲۰٬۰۰۰ کیلومتر.',
    specs: [['نوع فیلتر', 'پانلی'], ['طول', '۲۲۵', 'میلی‌متر'], ['عرض', '۱۷۰', 'میلی‌متر'], ['ارتفاع', '۴۸', 'میلی‌متر'], ['جنس قاب', 'پلی‌اورتان']],
    family: 'air-filter-pride-series',
    fitments: [
      { model: 'pride-131' },
      { model: 'tiba' },
      { model: 'saina' },
      { model: 'quick' },
    ],
    tags: ['فیلتر هوا', 'پراید', 'تیبا', 'ساینا'],
  },
  {
    sku: 'BRK-DISC-206R', oem: '424946', mpn: 'BD-206-R', title: 'دیسک ترمز عقب پژو ۲۰۶ تیپ ۵ (جفت)',
    titleEn: 'Rear Brake Disc Pair Peugeot 206 TIP5', category: 'brake-discs', brand: 'valeo',
    manufacturer: 'Valeo', price: 2_150_000, stock: 9,
    images: ['/demo/brake-disc.svg'], weight: 6_400, warranty: 12, country: 'فرانسه',
    description: 'جفت دیسک ترمز عقب توپر با پوشش ضدزنگ. مناسب خودروهای مجهز به ترمز دیسکی عقب.',
    specs: [['قطر', '۲۴۷', 'میلی‌متر'], ['ضخامت', '۹', 'میلی‌متر'], ['نوع', 'توپر'], ['تعداد پیچ', '۴', 'عدد'], ['تعداد در بسته', '۲', 'عدد']],
    family: 'brake-disc-rear-206',
    fitments: [
      { model: 'peugeot-206', trim: 'TIP5' },
    ],
    references: [{ type: 'CROSS_REFERENCE', number: 'DF4249', brand: 'TRW' }],
    tags: ['دیسک ترمز', 'عقب', 'پژو', '206'],
  },
];

/* ── shipping ───────────────────────────────────────────────────────── */

const SHIPPING_METHODS = [
  { code: 'post-pishtaz', kind: 'POST' as const, nameFa: 'پست پیشتاز', description: 'ارسال به سراسر کشور از طریق پست پیشتاز.',
    baseCost: 85_000, perKgCost: 18_000, freeOverSubtotal: 8_000_000, estimatedDaysMin: 2, estimatedDaysMax: 5,
    availableProvinces: [] as string[], sortOrder: 10 },
  { code: 'tipax', kind: 'STANDARD' as const, nameFa: 'باربری تیپاکس', description: 'مناسب بسته‌های سنگین و حجیم؛ کرایه در مقصد یا پیش‌پرداخت.',
    baseCost: 120_000, perKgCost: 12_000, freeOverSubtotal: null, estimatedDaysMin: 2, estimatedDaysMax: 4,
    availableProvinces: [], sortOrder: 20 },
  { code: 'tehran-courier', kind: 'COURIER' as const, nameFa: 'پیک موتوری تهران', description: 'ارسال با پیک در محدودهٔ شهر تهران (همان روز یا روز بعد).',
    baseCost: 95_000, perKgCost: 0, freeOverSubtotal: 5_000_000, estimatedDaysMin: 1, estimatedDaysMax: 1,
    availableProvinces: ['تهران', 'البرز'], sortOrder: 5 },
  { code: 'store-pickup', kind: 'PICKUP' as const, nameFa: 'تحویل حضوری در فروشگاه', description: 'دریافت سفارش از انبار فروشگاه پس از هماهنگی تلفنی.',
    baseCost: 0, perKgCost: 0, freeOverSubtotal: null, estimatedDaysMin: 1, estimatedDaysMax: 2,
    availableProvinces: ['تهران'], sortOrder: 1 },
];

const PROVINCE_SURCHARGES: { code: string; province: string; surcharge: number }[] = [
  { code: 'post-pishtaz', province: 'سیستان و بلوچستان', surcharge: 60_000 },
  { code: 'post-pishtaz', province: 'هرمزگان', surcharge: 45_000 },
  { code: 'post-pishtaz', province: 'خراسان جنوبی', surcharge: 40_000 },
  { code: 'post-pishtaz', province: 'تهران', surcharge: -20_000 },
];

/* ── run ────────────────────────────────────────────────────────────── */

async function main() {
  const db = getDb();
  console.log('▶ seeding demo data …');

  await withTransaction(async (tx) => {
    /* categories */
    const categoryIds = new Map<string, string>();
    for (const c of CATEGORIES) {
      const [row] = await tx
        .insert(categories)
        .values({
          slug: c.slug, nameFa: c.nameFa, nameEn: c.nameEn, description: c.description,
          imageUrl: c.image, icon: c.icon, sortOrder: CATEGORIES.indexOf(c) * 10, isActive: true,
          seoTitle: `${c.nameFa} | فروشگاه قطعات یدکی مِیدساخت`,
          seoDescription: c.description,
        })
        .onConflictDoUpdate({
          target: categories.slug,
          set: { nameFa: c.nameFa, description: c.description, imageUrl: c.image, icon: c.icon },
        })
        .returning({ id: categories.id });
      categoryIds.set(c.slug, row!.id);

      for (const child of c.children ?? []) {
        const [cr] = await tx
          .insert(categories)
          .values({
            slug: child.slug, nameFa: child.nameFa, nameEn: child.nameEn,
            parentId: row!.id, sortOrder: 0, isActive: true,
            seoTitle: `${child.nameFa} | ${c.nameFa}`,
            seoDescription: `خرید ${child.nameFa} با ضمانت اصالت کالا.`,
          })
          .onConflictDoUpdate({ target: categories.slug, set: { nameFa: child.nameFa, parentId: row!.id } })
          .returning({ id: categories.id });
        categoryIds.set(child.slug, cr!.id);
      }
    }
    console.log(`  ✔ ${categoryIds.size} categories`);

    /* brands */
    const brandIds = new Map<string, string>();
    for (const b of BRANDS) {
      const [row] = await tx
        .insert(brands)
        .values({ ...b, isActive: true, seoTitle: `قطعات ${b.nameFa}`, seoDescription: b.description })
        .onConflictDoUpdate({ target: brands.slug, set: { nameFa: b.nameFa, country: b.country, description: b.description } })
        .returning({ id: brands.id });
      brandIds.set(b.slug, row!.id);
    }
    console.log(`  ✔ ${brandIds.size} brands`);

    /* vehicles */
    const modelIds = new Map<string, string>();
    const engineIds = new Map<string, string>();
    const trimIds = new Map<string, string>();
    for (const vb of VEHICLES) {
      const [brandRow] = await tx
        .insert(vehicleBrands)
        .values({ slug: vb.slug, nameFa: vb.nameFa, nameEn: vb.nameEn, sortOrder: vb.sort, isActive: true })
        .onConflictDoUpdate({ target: vehicleBrands.slug, set: { nameFa: vb.nameFa, sortOrder: vb.sort } })
        .returning({ id: vehicleBrands.id });

      for (const m of vb.models) {
        const [modelRow] = await tx
          .insert(vehicleModels)
          .values({
            vehicleBrandId: brandRow!.id, slug: m.slug, nameFa: m.nameFa, nameEn: m.nameEn,
            yearFrom: m.yearFrom, yearTo: m.yearTo, isActive: true,
          })
          .onConflictDoUpdate({ target: vehicleModels.slug, set: { nameFa: m.nameFa, yearFrom: m.yearFrom, yearTo: m.yearTo } })
          .returning({ id: vehicleModels.id });
        modelIds.set(m.slug, modelRow!.id);

        for (const g of m.generations ?? []) {
          await tx
            .insert(vehicleGenerations)
            .values({
              vehicleModelId: modelRow!.id, code: g.code, nameFa: g.nameFa,
              yearFrom: g.yearFrom, yearTo: g.yearTo, isActive: true,
            })
            .onConflictDoUpdate({
              target: [vehicleGenerations.vehicleModelId, vehicleGenerations.code],
              set: { nameFa: g.nameFa },
            });
        }

        for (const t of m.trims ?? []) {
          const [trimRow] = await tx
            .insert(vehicleTrims)
            .values({ vehicleModelId: modelRow!.id, code: t.code, nameFa: t.nameFa, isActive: true })
            .onConflictDoUpdate({
              target: [vehicleTrims.vehicleModelId, vehicleTrims.code],
              set: { nameFa: t.nameFa },
            })
            .returning({ id: vehicleTrims.id });
          trimIds.set(`${m.slug}:${t.code}`, trimRow!.id);
        }

        for (const e of m.engines) {
          const [engineRow] = await tx
            .insert(vehicleEngines)
            .values({
              vehicleModelId: modelRow!.id, code: e.code, nameFa: e.nameFa,
              displacementCc: e.cc, fuelType: e.fuel, isActive: true,
            })
            .onConflictDoUpdate({
              target: [vehicleEngines.vehicleModelId, vehicleEngines.code],
              set: { nameFa: e.nameFa, displacementCc: e.cc },
            })
            .returning({ id: vehicleEngines.id });
          engineIds.set(`${m.slug}:${e.code}`, engineRow!.id);
        }
      }
    }
    console.log(`  ✔ ${modelIds.size} vehicle models, ${engineIds.size} engines, ${trimIds.size} trims`);

    /* products */
    for (const p of PRODUCTS) {
      const slug = p.title
        .replace(/[()،]/g, '')
        .replace(/\s+/g, '-')
        .replace(/-+/g, '-');

      const [row] = await tx
        .insert(products)
        .values({
          sku: p.sku, oemNumber: p.oem, mpn: p.mpn, slug,
          titleFa: p.title, titleEn: p.titleEn,
          descriptionFa: `${p.description}\n\n${DEMO_BANNER}`,
          categoryId: categoryIds.get(p.category) ?? null,
          brandId: brandIds.get(p.brand) ?? null,
          manufacturer: p.manufacturer,
          price: p.price, salePrice: p.salePrice ?? null,
          weightGrams: p.weight,
          warrantyMonths: p.warranty,
          countryOfOrigin: p.country,
          condition: p.condition ?? 'new',
          installationNotes: p.installation ?? null,
          productFamily: p.family ?? null,
          tags: p.tags,
          seoTitle: `${p.title} | خرید آنلاین قطعات یدکی`,
          seoDescription: p.description.slice(0, 300),
          isActive: true,
          publishedAt: new Date(),
        })
        .onConflictDoUpdate({
          target: products.sku,
          set: {
            titleFa: p.title, price: p.price, salePrice: p.salePrice ?? null,
            descriptionFa: `${p.description}\n\n${DEMO_BANNER}`, tags: p.tags,
            updatedAt: new Date(),
          },
        })
        .returning({ id: products.id });

      const productId = row!.id;

      await tx.delete(productImages).where(sql`product_id = ${productId}`);
      await tx.insert(productImages).values(
        p.images.map((url, i) => ({
          productId, url, alt: `تصویر ${p.title}`, sortOrder: i, isPrimary: i === 0,
        })),
      );

      await tx.delete(productSpecs).where(sql`product_id = ${productId}`);
      await tx.insert(productSpecs).values(
        p.specs.map(([key, value, unit], i) => ({
          productId, specKey: key, specValue: value, unit: unit ?? null, sortOrder: i,
        })),
      );

      await tx.delete(productFitments).where(sql`product_id = ${productId}`);
      for (const f of p.fitments) {
        const modelId = modelIds.get(f.model);
        if (!modelId) continue;
        const configurationId = await getOrCreateConfiguration(
          {
            vehicleModelId: modelId,
            vehicleTrimId: f.trim ? (trimIds.get(`${f.model}:${f.trim}`) ?? null) : null,
            vehicleEngineId: f.engine ? (engineIds.get(`${f.model}:${f.engine}`) ?? null) : null,
            yearFrom: f.yearFrom ?? null,
            yearTo: f.yearTo ?? null,
          },
          tx,
        );
        await tx
          .insert(productFitments)
          .values({
            productId,
            vehicleConfigurationId: configurationId,
            fitmentType: f.type ?? 'DIRECT',
            note: f.note ?? null,
            source: 'seed',
          })
          .onConflictDoNothing();
      }

      await tx.delete(productReferences).where(sql`product_id = ${productId}`);
      if (p.references && p.references.length > 0) {
        await tx.insert(productReferences).values(
          p.references.map((r) => ({
            productId,
            relationType: r.type,
            targetNumber: r.number,
            targetBrand: r.brand ?? null,
          })),
        );
      }

      await tx
        .insert(inventory)
        .values({ productId, quantityOnHand: p.stock, quantityReserved: 0, lowStockThreshold: 3 })
        .onConflictDoUpdate({ target: inventory.productId, set: { quantityOnHand: p.stock, quantityReserved: 0 } });

      await tx.insert(inventoryEvents).values({
        productId, type: 'RECEIVE', delta: p.stock,
        quantityOnHandAfter: p.stock, quantityReservedAfter: 0,
        reason: 'موجودی اولیه (داده نمایشی)',
      });
    }
    console.log(`  ✔ ${PRODUCTS.length} demo products`);

    /* shipping */
    const methodIds = new Map<string, string>();
    for (const m of SHIPPING_METHODS) {
      const [row] = await tx
        .insert(shippingMethods)
        .values({ ...m, isActive: true })
        .onConflictDoUpdate({
          target: shippingMethods.code,
          set: { nameFa: m.nameFa, baseCost: m.baseCost, perKgCost: m.perKgCost, freeOverSubtotal: m.freeOverSubtotal },
        })
        .returning({ id: shippingMethods.id });
      methodIds.set(m.code, row!.id);
    }
    for (const r of PROVINCE_SURCHARGES) {
      const methodId = methodIds.get(r.code);
      if (!methodId) continue;
      await tx
        .insert(shippingRates)
        .values({ methodId, province: r.province, costOverride: null, surcharge: r.surcharge })
        .onConflictDoUpdate({
          target: [shippingRates.methodId, shippingRates.province],
          set: { surcharge: r.surcharge },
        });
    }
    console.log(`  ✔ ${SHIPPING_METHODS.length} shipping methods`);

    /* store settings */
    const settings: [string, unknown][] = [
      ['store.name', 'مِیدساخت | فروشگاه قطعات یدکی خودرو'],
      ['store.tagline', 'قطعات یدکی اصل خودروهای ایرانی و وارداتی'],
      ['store.phone', '۰۲۱-۱۲۳۴۵۶۷۸'],
      ['store.email', 'info@example.invalid'],
      ['store.address', 'تهران، خیابان نمونه، پلاک ۱ (نشانی نمایشی)'],
      ['store.workingHours', 'شنبه تا چهارشنبه ۹ تا ۱۸ — پنجشنبه ۹ تا ۱۳'],
      ['store.isDemo', true],
      ['store.demoNotice', 'این یک فروشگاه نمایشی است. هیچ سفارش واقعی پردازش یا ارسال نمی‌شود.'],
      ['order.paymentTtlMinutes', 30],
    ];
    for (const [key, value] of settings) {
      await tx
        .insert(storeSettings)
        .values({ key, value: value as object })
        .onConflictDoUpdate({ target: storeSettings.key, set: { value: value as object, updatedAt: new Date() } });
    }
    console.log(`  ✔ ${settings.length} store settings`);
  });

  /* demo accounts */
  const adminHash = await hashPassword('Admin@12345');
  const customerHash = await hashPassword('Customer@12345');
  await db
    .insert(users)
    .values([
      { phone: '09120000000', fullName: 'مدیر نمایشی فروشگاه', email: 'admin@example.invalid', passwordHash: adminHash, role: 'admin' },
      { phone: '09121111111', fullName: 'مشتری نمایشی', email: 'customer@example.invalid', passwordHash: customerHash, role: 'customer' },
    ])
    .onConflictDoNothing();
  console.log('  ✔ demo accounts (admin 09120000000 / Admin@12345, customer 09121111111 / Customer@12345)');

  console.log('\n⚠  All seeded data is SYNTHETIC DEMO DATA — not real inventory, pricing or customers.\n');
}

main()
  .catch((e) => {
    console.error('✖ seed failed:', e);
    process.exitCode = 1;
  })
  .finally(() => closePool());
